cat > .env <<EOL
DATABASE_URL=$DATABASE_URL
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=$NEXTAUTH_URL
GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID
GITHUB_SECRET=$GITHUB_SECRET
EMAIL_SERVER_HOST=$EMAIL_SERVER_HOST
EMAIL_SERVER_PORT=$EMAIL_SERVER_PORT
EMAIL_SERVER_USER=$EMAIL_SERVER_USER
EMAIL_SERVER_PASSWORD=$EMAIL_SERVER_PASSWORD
EMAIL_FROM=$EMAIL_FROM
EOL