version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    rebase-strategy: all
    open-pull-requests-limit: 20
    reviewers:
      - trungnh99
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope